### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#1]
- [x] Création GDD
- [x] Implémentation déplacement
- [ ] Implémentation armes (1 mod secondaire par arme)
- [ ] Recherche artistique, mock-up character et armes
- [ ] Premier jet d'animation character
- [x] Test dans arène
- [x] Base narration
