### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#2]
- [ ] Implémentation de plusieurs ennemis de base
- [x] Implémentation weapons wheel
- [x] Implémentation des munitions
- [ ] Création assets du personnages et des armes
- [ ] Mock-up ennemis et d'un boss
- [ ] Test dans arène
