### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#3]
- [ ] Ajout d'un boss
- [ ] Implémentation menu changement de mod
- [ ] Implémentation d'un second mod par arme
- [ ] Création assets ennemis de base
- [ ] Création assets boss
- [ ] Mock-up environnement
