### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#4]
- [ ] Implémentation des pièges et obstacles
- [ ] Script de génération procédurale
- [ ] Création assets environnement
- [ ] Mock-up UI
