### ISSUE TITLE
Milestone 5

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#5]
- [ ] Prototypage arbres de talents
- [ ] Implémentation UI
- [ ] Création assets UI
- [ ] Mock-up ennemis spéciaux et second boss
