### ISSUE TITLE
Milestone 6

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#6]
- [ ] Design objets aléatoires 
- [ ] Ajout objets aléatoires
- [ ] Implémentation second boss
- [ ] Ébauche progression du joueur
