### ISSUE TITLE
Milestone 7

### ISSUE THREAD

**Issue by Nylash** [Nylash/AtomicNanny#7]
- [ ] Implémentation des arbres de talents
- [ ] Création assets ennemis spéciaux
- [ ] Enrichissement narration
- [ ] Implémentation base narration
